{{- if .Values.appEnvs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $key, $value := .Values.appEnvs }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
